//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.17 at 09:51:12 AM EDT 
//


package org.kuali.ext.mm.b2b.cxml.kfs.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * org.kuali.ext.mm.b2b.cxml.kfs.types package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java
 * representation of XML content can consist of schema derived interfaces and classes representing the binding of schema type
 * definitions, element declarations and model groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CXMLRequestInvoiceDetailRequestInvoiceDetailOrderInvoiceDetailOrderInfo_QNAME = new QName(
        "http://www.kuali.org/kfs/purap/electronicInvoice", "InvoiceDetailOrderInfo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * org.kuali.ext.mm.b2b.cxml.kfs.types
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PostalAddress.Country }
     */
    public PostalAddress.Country createPostalAddressCountry() {
        return new PostalAddress.Country();
    }

    /**
     * Create an instance of {@link InvoiceDetailItem.InvoiceDetailItemReference.Country }
     */
    public InvoiceDetailItem.InvoiceDetailItemReference.Country createInvoiceDetailItemInvoiceDetailItemReferenceCountry() {
        return new InvoiceDetailItem.InvoiceDetailItemReference.Country();
    }

    /**
     * Create an instance of {@link InvoiceDetailServiceItem.SubtotalAmount }
     */
    public SubtotalAmount createInvoiceDetailServiceItemSubtotalAmount() {
        return new SubtotalAmount();
    }

    /**
     * Create an instance of {@link SupplierOrderInfo }
     */
    public SupplierOrderInfo createSupplierOrderInfo() {
        return new SupplierOrderInfo();
    }

    /**
     * Create an instance of {@link PostalAddress }
     */
    public PostalAddress createPostalAddress() {
        return new PostalAddress();
    }

    /**
     * Create an instance of {@link InvoiceDetailAdditionalChargesItem.InvoiceDetailAdditionalChargesItemReference }
     */
    public InvoiceDetailAdditionalChargesItem.InvoiceDetailAdditionalChargesItemReference createInvoiceDetailAdditionalChargesItemInvoiceDetailAdditionalChargesItemReference() {
        return new InvoiceDetailAdditionalChargesItem.InvoiceDetailAdditionalChargesItemReference();
    }

    /**
     * Create an instance of {@link InvoiceDetailServiceItem.InvoiceDetailServiceItemReference }
     */
    public InvoiceDetailServiceItem.InvoiceDetailServiceItemReference createInvoiceDetailServiceItemInvoiceDetailServiceItemReference() {
        return new InvoiceDetailServiceItem.InvoiceDetailServiceItemReference();
    }

    /**
     * Create an instance of {@link InvoiceDetailServiceItem }
     */
    public InvoiceDetailServiceItem createInvoiceDetailServiceItem() {
        return new InvoiceDetailServiceItem();
    }

    /**
     * Create an instance of {@link SubtotalAmount }
     */
    public SubtotalAmount createCXMLRequestInvoiceDetailRequestInvoiceDetailSummarySubtotalAmount() {
        return new SubtotalAmount();
    }

    /**
     * Create an instance of {@link CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader.InvoiceDetailLineIndicator }
     */
    public CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader.InvoiceDetailLineIndicator createCXMLRequestInvoiceDetailRequestInvoiceDetailRequestHeaderInvoiceDetailLineIndicator() {
        return new CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader.InvoiceDetailLineIndicator();
    }

    /**
     * Create an instance of {@link InvoiceDetailItem.InvoiceDetailItemReference }
     */
    public InvoiceDetailItem.InvoiceDetailItemReference createInvoiceDetailItemInvoiceDetailItemReference() {
        return new InvoiceDetailItem.InvoiceDetailItemReference();
    }

    /**
     * Create an instance of {@link OrderIDInfo }
     */
    public OrderIDInfo createOrderIDInfo() {
        return new OrderIDInfo();
    }

    /**
     * Create an instance of {@link Credential }
     */
    public Credential createCredential() {
        return new Credential();
    }

    /**
     * Create an instance of {@link CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader.InvoicePartner.IdReference }
     */
    public CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader.InvoicePartner.IdReference createCXMLRequestInvoiceDetailRequestInvoiceDetailRequestHeaderInvoicePartnerIdReference() {
        return new CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader.InvoicePartner.IdReference();
    }

    /**
     * Create an instance of {@link InvoiceDetailAdditionalChargesItem.InvoiceDetailLineShipping }
     */
    public InvoiceDetailAdditionalChargesItem.InvoiceDetailLineShipping createInvoiceDetailAdditionalChargesItemInvoiceDetailLineShipping() {
        return new InvoiceDetailAdditionalChargesItem.InvoiceDetailLineShipping();
    }

    /**
     * Create an instance of {@link Comments }
     */
    public Comments createComments() {
        return new Comments();
    }

    /**
     * Create an instance of {@link OrderReference.DocumentReference }
     */
    public OrderReference.DocumentReference createOrderReferenceDocumentReference() {
        return new OrderReference.DocumentReference();
    }

    /**
     * Create an instance of {@link Description }
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link InvoiceDetailServiceItem.InvoiceDetailLineShipping }
     */
    public InvoiceDetailServiceItem.InvoiceDetailLineShipping createInvoiceDetailServiceItemInvoiceDetailLineShipping() {
        return new InvoiceDetailServiceItem.InvoiceDetailLineShipping();
    }

    /**
     * Create an instance of {@link Fax }
     */
    public Fax createFax() {
        return new Fax();
    }

    /**
     * Create an instance of {@link InvoiceDetailShipping.DocumentReference }
     */
    public InvoiceDetailShipping.DocumentReference createInvoiceDetailShippingDocumentReference() {
        return new InvoiceDetailShipping.DocumentReference();
    }

    /**
     * Create an instance of {@link CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader.InvoicePartner }
     */
    public CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader.InvoicePartner createCXMLRequestInvoiceDetailRequestInvoiceDetailRequestHeaderInvoicePartner() {
        return new CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader.InvoicePartner();
    }

    /**
     * Create an instance of {@link InvoiceDetailShipping }
     */
    public InvoiceDetailShipping createInvoiceDetailShipping() {
        return new InvoiceDetailShipping();
    }

    /**
     * Create an instance of {@link UnitPrice }
     */
    public UnitPrice createUnitPrice() {
        return new UnitPrice();
    }

    /**
     * Create an instance of {@link CXML.Request.InvoiceDetailRequest.InvoiceDetailOrder.InvoiceDetailOrderInfo }
     */
    public CXML.Request.InvoiceDetailRequest.InvoiceDetailOrder.InvoiceDetailOrderInfo createCXMLRequestInvoiceDetailRequestInvoiceDetailOrderInvoiceDetailOrderInfo() {
        return new CXML.Request.InvoiceDetailRequest.InvoiceDetailOrder.InvoiceDetailOrderInfo();
    }

    /**
     * Create an instance of {@link CXML.Request.InvoiceDetailRequest.InvoiceDetailSummary }
     */
    public CXML.Request.InvoiceDetailRequest.InvoiceDetailSummary createCXMLRequestInvoiceDetailRequestInvoiceDetailSummary() {
        return new CXML.Request.InvoiceDetailRequest.InvoiceDetailSummary();
    }

    /**
     * Create an instance of {@link InvoiceDetailItem.InvoiceDetailItemReference.ItemID }
     */
    public InvoiceDetailItem.InvoiceDetailItemReference.ItemID createInvoiceDetailItemInvoiceDetailItemReferenceItemID() {
        return new InvoiceDetailItem.InvoiceDetailItemReference.ItemID();
    }

    /**
     * Create an instance of {@link InvoiceDetailItem.InvoiceDetailLineShipping }
     */
    public InvoiceDetailItem.InvoiceDetailLineShipping createInvoiceDetailItemInvoiceDetailLineShipping() {
        return new InvoiceDetailItem.InvoiceDetailLineShipping();
    }

    /**
     * Create an instance of {@link InvoiceDetailServiceItem.InvoiceDetailServiceItemReference.ItemID }
     */
    public InvoiceDetailServiceItem.InvoiceDetailServiceItemReference.ItemID createInvoiceDetailServiceItemInvoiceDetailServiceItemReferenceItemID() {
        return new InvoiceDetailServiceItem.InvoiceDetailServiceItemReference.ItemID();
    }

    /**
     * Create an instance of {@link GrossAmount }
     */
    public GrossAmount createGrossAmount() {
        return new GrossAmount();
    }

    /**
     * Create an instance of {@link InvoiceDetailServiceItem.InvoiceDetailServiceItemReference.Country }
     */
    public InvoiceDetailServiceItem.InvoiceDetailServiceItemReference.Country createInvoiceDetailServiceItemInvoiceDetailServiceItemReferenceCountry() {
        return new InvoiceDetailServiceItem.InvoiceDetailServiceItemReference.Country();
    }

    /**
     * Create an instance of {@link CXML.Header }
     */
    public CXML.Header createCXMLHeader() {
        return new CXML.Header();
    }

    /**
     * Create an instance of {@link Contact }
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link InvoiceDetailAdditionalChargesItem }
     */
    public InvoiceDetailAdditionalChargesItem createInvoiceDetailAdditionalChargesItem() {
        return new InvoiceDetailAdditionalChargesItem();
    }

    /**
     * Create an instance of {@link MasterAgreementIDInfo }
     */
    public MasterAgreementIDInfo createMasterAgreementIDInfo() {
        return new MasterAgreementIDInfo();
    }

    /**
     * Create an instance of {@link Phone.TelephoneNumber }
     */
    public Phone.TelephoneNumber createPhoneTelephoneNumber() {
        return new Phone.TelephoneNumber();
    }

    /**
     * Create an instance of {@link InvoiceDetailItem.InvoiceDetailItemReference.ManufacturerName }
     */
    public InvoiceDetailItem.InvoiceDetailItemReference.ManufacturerName createInvoiceDetailItemInvoiceDetailItemReferenceManufacturerName() {
        return new InvoiceDetailItem.InvoiceDetailItemReference.ManufacturerName();
    }

    /**
     * Create an instance of {@link InvoiceDetailAdditionalChargesItem.SubtotalAmount }
     */
    public SubtotalAmount createInvoiceDetailAdditionalChargesItemSubtotalAmount() {
        return new SubtotalAmount();
    }

    /**
     * Create an instance of {@link Tax.TaxDetail.TaxLocation }
     */
    public Tax.TaxDetail.TaxLocation createTaxTaxDetailTaxLocation() {
        return new Tax.TaxDetail.TaxLocation();
    }

    /**
     * Create an instance of {@link CXML.Request.InvoiceDetailRequest.InvoiceDetailSummary.DueAmount }
     */
    public CXML.Request.InvoiceDetailRequest.InvoiceDetailSummary.DueAmount createCXMLRequestInvoiceDetailRequestInvoiceDetailSummaryDueAmount() {
        return new CXML.Request.InvoiceDetailRequest.InvoiceDetailSummary.DueAmount();
    }

    /**
     * Create an instance of {@link Fax.TelephoneNumber.CountryCode }
     */
    public Fax.TelephoneNumber.CountryCode createFaxTelephoneNumberCountryCode() {
        return new Fax.TelephoneNumber.CountryCode();
    }

    /**
     * Create an instance of {@link CXML.Header.To }
     */
    public CXML.Header.To createCXMLHeaderTo() {
        return new CXML.Header.To();
    }

    /**
     * Create an instance of {@link CXML.Request.InvoiceDetailRequest.InvoiceDetailSummary.ShippingAmount }
     */
    public CXML.Request.InvoiceDetailRequest.InvoiceDetailSummary.ShippingAmount createCXMLRequestInvoiceDetailRequestInvoiceDetailSummaryShippingAmount() {
        return new CXML.Request.InvoiceDetailRequest.InvoiceDetailSummary.ShippingAmount();
    }

    /**
     * Create an instance of {@link Phone }
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link MasterAgreementReference }
     */
    public MasterAgreementReference createMasterAgreementReference() {
        return new MasterAgreementReference();
    }

    /**
     * Create an instance of {@link InvoiceDetailServiceItem.InvoiceDetailLineSpecialHandling }
     */
    public InvoiceDetailServiceItem.InvoiceDetailLineSpecialHandling createInvoiceDetailServiceItemInvoiceDetailLineSpecialHandling() {
        return new InvoiceDetailServiceItem.InvoiceDetailLineSpecialHandling();
    }

    /**
     * Create an instance of {@link Phone.TelephoneNumber.CountryCode }
     */
    public Phone.TelephoneNumber.CountryCode createPhoneTelephoneNumberCountryCode() {
        return new Phone.TelephoneNumber.CountryCode();
    }

    /**
     * Create an instance of {@link Tax.TaxDetail.TaxableAmount }
     */
    public Tax.TaxDetail.TaxableAmount createTaxTaxDetailTaxableAmount() {
        return new Tax.TaxDetail.TaxableAmount();
    }

    /**
     * Create an instance of {@link NetAmount }
     */
    public NetAmount createNetAmount() {
        return new NetAmount();
    }

    /**
     * Create an instance of {@link CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader.InvoiceDetailHeaderIndicator }
     */
    public CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader.InvoiceDetailHeaderIndicator createCXMLRequestInvoiceDetailRequestInvoiceDetailRequestHeaderInvoiceDetailHeaderIndicator() {
        return new CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader.InvoiceDetailHeaderIndicator();
    }

    /**
     * Create an instance of {@link Tax }
     */
    public Tax createTax() {
        return new Tax();
    }

    /**
     * Create an instance of {@link InvoiceDetailShipping.CarrierIdentifier }
     */
    public InvoiceDetailShipping.CarrierIdentifier createInvoiceDetailShippingCarrierIdentifier() {
        return new InvoiceDetailShipping.CarrierIdentifier();
    }

    /**
     * Create an instance of {@link CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader.PaymentTerm }
     */
    public CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader.PaymentTerm createCXMLRequestInvoiceDetailRequestInvoiceDetailRequestHeaderPaymentTerm() {
        return new CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader.PaymentTerm();
    }

    /**
     * Create an instance of {@link CXML.Request }
     */
    public CXML.Request createCXMLRequest() {
        return new CXML.Request();
    }

    /**
     * Create an instance of {@link Fax.TelephoneNumber }
     */
    public Fax.TelephoneNumber createFaxTelephoneNumber() {
        return new Fax.TelephoneNumber();
    }

    /**
     * Create an instance of {@link URL }
     */
    public URL createURL() {
        return new URL();
    }

    /**
     * Create an instance of {@link Email }
     */
    public Email createEmail() {
        return new Email();
    }

    /**
     * Create an instance of {@link InvoiceDetailAdditionalChargesItem.InvoiceDetailLineSpecialHandling }
     */
    public InvoiceDetailAdditionalChargesItem.InvoiceDetailLineSpecialHandling createInvoiceDetailAdditionalChargesItemInvoiceDetailLineSpecialHandling() {
        return new InvoiceDetailAdditionalChargesItem.InvoiceDetailLineSpecialHandling();
    }

    /**
     * Create an instance of {@link CXML.Request.InvoiceDetailRequest }
     */
    public CXML.Request.InvoiceDetailRequest createCXMLRequestInvoiceDetailRequest() {
        return new CXML.Request.InvoiceDetailRequest();
    }

    /**
     * Create an instance of {@link InvoiceDetailItem.InvoiceDetailLineSpecialHandling }
     */
    public InvoiceDetailItem.InvoiceDetailLineSpecialHandling createInvoiceDetailItemInvoiceDetailLineSpecialHandling() {
        return new InvoiceDetailItem.InvoiceDetailLineSpecialHandling();
    }

    /**
     * Create an instance of {@link Name }
     */
    public Name createName() {
        Name name = new Name();
        name.setLang("en");
        return name;
    }

    /**
     * Create an instance of {@link CXML.Request.InvoiceDetailRequest.InvoiceDetailOrder }
     */
    public CXML.Request.InvoiceDetailRequest.InvoiceDetailOrder createCXMLRequestInvoiceDetailRequestInvoiceDetailOrder() {
        return new CXML.Request.InvoiceDetailRequest.InvoiceDetailOrder();
    }

    /**
     * Create an instance of {@link Tax.TaxDetail.TaxAmount }
     */
    public Tax.TaxDetail.TaxAmount createTaxTaxDetailTaxAmount() {
        return new Tax.TaxDetail.TaxAmount();
    }

    /**
     * Create an instance of {@link CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader }
     */
    public CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader createCXMLRequestInvoiceDetailRequestInvoiceDetailRequestHeader() {
        return new CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader();
    }

    /**
     * Create an instance of {@link CXML }
     */
    public CXML createCXML() {
        return new CXML();
    }

    /**
     * Create an instance of {@link OrderReference }
     */
    public OrderReference createOrderReference() {
        return new OrderReference();
    }

    /**
     * Create an instance of {@link Tax.TaxDetail }
     */
    public Tax.TaxDetail createTaxTaxDetail() {
        return new Tax.TaxDetail();
    }

    /**
     * Create an instance of {@link InvoiceDetailAdditionalChargesItem.InvoiceDetailAdditionalChargesItemReference.ItemID }
     */
    public InvoiceDetailAdditionalChargesItem.InvoiceDetailAdditionalChargesItemReference.ItemID createInvoiceDetailAdditionalChargesItemInvoiceDetailAdditionalChargesItemReferenceItemID() {
        return new InvoiceDetailAdditionalChargesItem.InvoiceDetailAdditionalChargesItemReference.ItemID();
    }

    /**
     * Create an instance of {@link Money }
     */
    public Money createMoney() {
        return new Money();
    }

    /**
     * Create an instance of {@link Extrinsic }
     */
    public Extrinsic createExtrinsic() {
        return new Extrinsic();
    }

    /**
     * Create an instance of {@link InvoiceDetailAdditionalChargesItem.InvoiceDetailAdditionalChargesItemReference.Country }
     */
    public InvoiceDetailAdditionalChargesItem.InvoiceDetailAdditionalChargesItemReference.Country createInvoiceDetailAdditionalChargesItemInvoiceDetailAdditionalChargesItemReferenceCountry() {
        return new InvoiceDetailAdditionalChargesItem.InvoiceDetailAdditionalChargesItemReference.Country();
    }

    /**
     * Create an instance of {@link InvoiceDetailServiceItem.InvoiceDetailServiceItemReference.ManufacturerName }
     */
    public InvoiceDetailServiceItem.InvoiceDetailServiceItemReference.ManufacturerName createInvoiceDetailServiceItemInvoiceDetailServiceItemReferenceManufacturerName() {
        return new InvoiceDetailServiceItem.InvoiceDetailServiceItemReference.ManufacturerName();
    }

    /**
     * Create an instance of {@link InvoiceDetailItem }
     */
    public InvoiceDetailItem createInvoiceDetailItem() {
        return new InvoiceDetailItem();
    }

    /**
     * Create an instance of {@link CXML.Header.Sender }
     */
    public CXML.Header.Sender createCXMLHeaderSender() {
        return new CXML.Header.Sender();
    }

    /**
     * Create an instance of {@link CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader.InvoiceDetailPaymentTerm }
     */
    public CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader.InvoiceDetailPaymentTerm createCXMLRequestInvoiceDetailRequestInvoiceDetailRequestHeaderInvoiceDetailPaymentTerm() {
        return new CXML.Request.InvoiceDetailRequest.InvoiceDetailRequestHeader.InvoiceDetailPaymentTerm();
    }

    /**
     * Create an instance of {@link CXML.Request.InvoiceDetailRequest.InvoiceDetailSummary.SpecialHandlingAmount }
     */
    public CXML.Request.InvoiceDetailRequest.InvoiceDetailSummary.SpecialHandlingAmount createCXMLRequestInvoiceDetailRequestInvoiceDetailSummarySpecialHandlingAmount() {
        return new CXML.Request.InvoiceDetailRequest.InvoiceDetailSummary.SpecialHandlingAmount();
    }

    /**
     * Create an instance of
     * {@link InvoiceDetailAdditionalChargesItem.InvoiceDetailAdditionalChargesItemReference.ManufacturerName }
     */
    public InvoiceDetailAdditionalChargesItem.InvoiceDetailAdditionalChargesItemReference.ManufacturerName createInvoiceDetailAdditionalChargesItemInvoiceDetailAdditionalChargesItemReferenceManufacturerName() {
        return new InvoiceDetailAdditionalChargesItem.InvoiceDetailAdditionalChargesItemReference.ManufacturerName();
    }

    /**
     * Create an instance of {@link InvoiceDetailItem.SubtotalAmount }
     */
    public SubtotalAmount createInvoiceDetailItemSubtotalAmount() {
        return new SubtotalAmount();
    }

    /**
     * Create an instance of {@link InvoiceDetailDiscount }
     */
    public InvoiceDetailDiscount createInvoiceDetailDiscount() {
        return new InvoiceDetailDiscount();
    }

    /**
     * Create an instance of {@link CXML.Header.From }
     */
    public CXML.Header.From createCXMLHeaderFrom() {
        return new CXML.Header.From();
    }

    /**
     * Create an instance of {@link CXML.Request.InvoiceDetailRequest.InvoiceDetailSummary.DepositAmount }
     */
    public CXML.Request.InvoiceDetailRequest.InvoiceDetailSummary.DepositAmount createCXMLRequestInvoiceDetailRequestInvoiceDetailSummaryDepositAmount() {
        return new CXML.Request.InvoiceDetailRequest.InvoiceDetailSummary.DepositAmount();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CXML.Request.InvoiceDetailRequest.InvoiceDetailOrder.InvoiceDetailOrderInfo }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.kuali.org/kfs/purap/electronicInvoice", name = "InvoiceDetailOrderInfo", scope = CXML.Request.InvoiceDetailRequest.InvoiceDetailOrder.class)
    public JAXBElement<CXML.Request.InvoiceDetailRequest.InvoiceDetailOrder.InvoiceDetailOrderInfo> createCXMLRequestInvoiceDetailRequestInvoiceDetailOrderInvoiceDetailOrderInfo(
            CXML.Request.InvoiceDetailRequest.InvoiceDetailOrder.InvoiceDetailOrderInfo value) {
        return new JAXBElement<CXML.Request.InvoiceDetailRequest.InvoiceDetailOrder.InvoiceDetailOrderInfo>(
            _CXMLRequestInvoiceDetailRequestInvoiceDetailOrderInvoiceDetailOrderInfo_QNAME,
            CXML.Request.InvoiceDetailRequest.InvoiceDetailOrder.InvoiceDetailOrderInfo.class,
            CXML.Request.InvoiceDetailRequest.InvoiceDetailOrder.class, value);
    }

}
