//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 02:56:33 PM EDT 
//


package org.kuali.ext.mm.b2b.cxml.types;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}InvoiceDetailOrderInfo"/>
 *         &lt;element ref="{}InvoiceDetailOrderSummary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "invoiceDetailOrderInfo",
    "invoiceDetailOrderSummary"
})
@XmlRootElement(name = "InvoiceDetailHeaderOrder")
public class InvoiceDetailHeaderOrder {

    @XmlElement(name = "InvoiceDetailOrderInfo", required = true)
    protected InvoiceDetailOrderInfo invoiceDetailOrderInfo;
    @XmlElement(name = "InvoiceDetailOrderSummary", required = true)
    protected InvoiceDetailOrderSummary invoiceDetailOrderSummary;

    /**
     * Gets the value of the invoiceDetailOrderInfo property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceDetailOrderInfo }
     *     
     */
    public InvoiceDetailOrderInfo getInvoiceDetailOrderInfo() {
        return invoiceDetailOrderInfo;
    }

    /**
     * Sets the value of the invoiceDetailOrderInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceDetailOrderInfo }
     *     
     */
    public void setInvoiceDetailOrderInfo(InvoiceDetailOrderInfo value) {
        this.invoiceDetailOrderInfo = value;
    }

    /**
     * Gets the value of the invoiceDetailOrderSummary property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceDetailOrderSummary }
     *     
     */
    public InvoiceDetailOrderSummary getInvoiceDetailOrderSummary() {
        return invoiceDetailOrderSummary;
    }

    /**
     * Sets the value of the invoiceDetailOrderSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceDetailOrderSummary }
     *     
     */
    public void setInvoiceDetailOrderSummary(InvoiceDetailOrderSummary value) {
        this.invoiceDetailOrderSummary = value;
    }

}
