//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.21 at 02:56:33 PM EDT 
//


package org.kuali.ext.mm.b2b.cxml.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}Status" minOccurs="0"/>
 *         &lt;element ref="{}cxml.messages"/>
 *       &lt;/choice>
 *       &lt;attribute name="deploymentMode" default="production">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="production"/>
 *             &lt;enumeration value="test"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="inReplyTo" type="{}string" />
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "status",
    "cxmlMessages"
})
@XmlRootElement(name = "Message")
public class Message {

    @XmlElement(name = "Status")
    protected Status status;
    @XmlElementRef(name = "cxml.messages", type = JAXBElement.class)
    protected JAXBElement<?> cxmlMessages;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String deploymentMode;
    @XmlAttribute
    protected String inReplyTo;
    @XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the cxmlMessages property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DataAvailableMessage }{@code >}
     *     {@link JAXBElement }{@code <}{@link java.lang.Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link SupplierChangeMessage }{@code >}
     *     {@link JAXBElement }{@code <}{@link SubscriptionChangeMessage }{@code >}
     *     {@link JAXBElement }{@code <}{@link ProviderDoneMessage }{@code >}
     *     {@link JAXBElement }{@code <}{@link PunchOutOrderMessage }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrganizationChangeMessage }{@code >}
     *     
     */
    public JAXBElement<?> getCxmlMessages() {
        return cxmlMessages;
    }

    /**
     * Sets the value of the cxmlMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DataAvailableMessage }{@code >}
     *     {@link JAXBElement }{@code <}{@link java.lang.Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link SupplierChangeMessage }{@code >}
     *     {@link JAXBElement }{@code <}{@link SubscriptionChangeMessage }{@code >}
     *     {@link JAXBElement }{@code <}{@link ProviderDoneMessage }{@code >}
     *     {@link JAXBElement }{@code <}{@link PunchOutOrderMessage }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrganizationChangeMessage }{@code >}
     *     
     */
    public void setCxmlMessages(JAXBElement<?> value) {
        this.cxmlMessages = ((JAXBElement<?> ) value);
    }

    /**
     * Gets the value of the deploymentMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeploymentMode() {
        if (deploymentMode == null) {
            return "production";
        } else {
            return deploymentMode;
        }
    }

    /**
     * Sets the value of the deploymentMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeploymentMode(String value) {
        this.deploymentMode = value;
    }

    /**
     * Gets the value of the inReplyTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInReplyTo() {
        return inReplyTo;
    }

    /**
     * Sets the value of the inReplyTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInReplyTo(String value) {
        this.inReplyTo = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
